
__dependency__: configs/elias.yaml

# General parameters
expname: 'elias-2-def-final' # Experiment name
dataset: LF-Wikipedia-500K-Aug-Soft-Best # Dataset name 
net: elias-2 # Network class identifier
loss: elias-loss # Loss class identifier
tf_max_len: 256 # Maximum input sequence length of transformer
resume_path: Results/[project]/[dataset]/elias-1-def-final-lr-enc-5e-5-lr-clf-0.005-loss-lam-0.05/model.pt

# Network parameters
A_init_path: Results/[project]/[dataset]/elias-1-def-final-lr-enc-5e-5-lr-clf-0.005-loss-lam-0.05/A_approx.npz # Initialize label-cluster adjacency matrix from this file (expects *.npz file)
loss_lambda: 0.05

# Training parameters
num_epochs: 25 # Number of epochs
bsz: 128 # Mini-batch size
w_accumulation_steps: 10 # It's more efficient to apply weight updates to classification matrix after every specified accumulation steps
lr:  0.005 # Learning rate for network parameters
lr_wl: 0.005 # Learning rate for the classifier matrix (W_l) parameters
lr_tf: 5.0e-5 # Learning rate for the transformer encoder (\phi) parameters
use_swa: True # Use stochastic weighted averaging (SWA) trick, can give minor improvements in results
swa_start: 8 # SWA start epoch
swa_step: 500 # SWA step size
