# Dependencies can be ',' separated .yaml filenames
__dependency__: configs/elias.yaml

# General parameters
expname: 'ELIAS-1-loss_lamb_0.05-lr_clf_0.005-lr_enc_5e-5-bs_256-num_clusters_8192' # Experiment name
desc: 'Stage 1 of ELIAS training'
dataset: 'LF-Wikipedia-500K' # Dataset name 
net: elias-1 # Network class identifier
tf_max_len: 256 # Maximum input sequence length of transformer
data_dir: './Datasets'
# Network parameters
A_init_path: './Results/[project]/[dataset]/[expname]/cmat.npz' # Initialize label-cluster adjacency matrix from this file (expects *.npz file)
loss_lambda: 0.05 # Weight to shortlist loss in the total loss, L = L_classification + \lambda * L_shortlist

# Training parameters
num_epochs: 10 # Number of epochs
bsz: 256 # Mini-batch size
w_accumulation_steps: 1 # It's more efficient to apply weight updates to classification matrix after every specified accumulation steps
lr: 0.005 # Learning rate for network parameters
lr_wl: 0.005 # Learning rate for the classifier matrix (W_l) parameters
lr_tf: 5.0e-5 # Learning rate for the transformer encoder (\phi) parameters
max_leaf: 64 # 8192 clusters will be there
