
__dependency__: configs/ShoppingAds-100K/elias-1.yaml

# General parameters
expname: 'ELIAS-2' # Experiment name
net: elias-2 # Network class identifier
resume_path: Results/[project]/[dataset]/ELIAS-1/model.pt

# Network parameters
A_init_path: Results/[project]/[dataset]/ELIAS-1/A_approx.npz # Initialize label-cluster adjacency matrix from this file (expects *.npz file)
loss_lambda: 0.05 # Weight to shortlist loss in the total loss, L = L_classification + \lambda * L_shortlist
ranker_calibrate: False # Calibrate ranker scores and elias scores

# Training parameters
num_epochs: 20 # Number of epochs
lr: 3.e-5 # Learning rate for network parameters
lr_wl: 0.006 # Learning rate for the classifier matrix (W_l) parameters
lr_tf: 6.e-6 # Learning rate for the transformer encoder (\phi) parameters
