# Dependencies can be ',' separated .yaml filenames
__dependency__: configs/elias.yaml

# General parameters
expname: 'ELIAS-1' # Experiment name
desc: 'Stage 1 of ELIAS training'
dataset: 'amazon-670k' # Dataset name 
net: elias-1 # Network class identifier
tf: bert-base-uncased # Name of transformer encoder to be used in the model, all huggingface transformer model names are applicable
tf_max_len: 128 # Maximum input sequence length of transformer

# Network parameters
A_init_path: 'Results/[project]/[dataset]/[expname]/cmat.npz' # Initialize label-cluster adjacency matrix from this file (expects *.npz file)
loss_lambda: 0.05 # Weight to shortlist loss in the total loss, L = L_classification + \lambda * L_shortlist

# Training parameters
amp_encode: True
num_epochs: 30 # Number of epochs
bsz: 256 # Mini-batch size
w_accumulation_steps: 1 # It's more efficient to apply weight updates to classification matrix after every specified accumulation steps
lr: 0.003 # Learning rate for network parameters
lr_wl: 0.003 # Learning rate for the classifier matrix (W_l) parameters
lr_tf: 1.0e-4 # Learning rate for the transformer encoder (\phi) parameters